#!/usr/bin/env bash
#
# Find and open in a text editor first found file by filename.

if [[ -z "${1}" ]]; then
    echo "usage: ${0##*/} filename.ext or ${0##*/} filename.ext w"
elif [[ "${2}" == "w" ]]; then
    vim $(find . -iname *${1}*)
else
    vim $(find . -iname ${1}*)
fi
